image: floaterest/note:latest

variables:
  PIPELINES: $CI_API_V4_URL/projects/$CI_PROJECT_ID/pipelines

pages:
  before_script:
    - pnpm install --frozen-lockfile
  cache:
    - key:
        files: [ pnpm-lock.yaml ]
      paths:
        - .pnpm-store
    - key: tectonic
      paths:
        - /root/.cache/Tectonic
    - key: graphics
      paths:
        - public/**/*.pdf
        - public/**/*.svg
  script:
    - 'tree public # includes cached files'
    - pnpm run build
    - | # remove pdf/svg with no tex
      comm -23 <(find dist -name  '*.pdf' | cut -d"." -f1 | sort) <(find dist -name  '*.tex' | cut -d"." -f1 | sort) \
      | xargs -t -I{} rm -rf '{}.pdf' '{}.svg'
    - tree dist # bulid
    - rm public -rf && mv dist public
    - | # keep only 4 newest pipelines
      curl -H "PRIVATE-TOKEN: $TOKEN" "$PIPELINES?sort=desc" \
      | jq '.[4:][].id' \
      | xargs -I{} curl -H "PRIVATE-TOKEN: $TOKEN" -X "DELETE" "$PIPELINES/{}"
  artifacts:
    paths: [ public ]
