name: Build

on:
  push:
    branches:
      - note
    # branches-ignore: [ 'master' ]

env:
  message: (≧ω≦) Update
  remote: https://git:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git

jobs:
  build:
    name: Generate HTML
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Pandoc
        run: python3 pandoc.py && pandoc --version
      - name: Clone Last Build
        run: |
          git pull
          git rev-parse -q --verify origin/build
          make branch
      - name: Build HTML
        run: npm i && make -B

      - name: Deploy to Github Pages
        run : |
          cd build
          tree -I node_modules
          git init
          git config --global user.email "support+actions@github.com"
          git config --global user.name "GitHub Actions"
          git config --global init.defaultBranch master
          git remote set-url origin ${{ env.remote }} || git remote add origin ${{ env.remote }}
          git checkout -b build
          git add .
          git commit -m "${{ env.message }}"
          git push -u origin build -f
