name: Build

on: 
  push: 
    branches: 
      - note

env:
  message: (≧ω≦) Update
  remote: https://git:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git

jobs:
  build:
    name: Generate HTML
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install TexLive
        run: sh src/texlive.sh

      - name: Update PATH
        run: |
          echo "$(pwd)/texlive/bin/x86_64-linux:$PATH" >> $GITHUB_PATH
          export PATH=$GITHUB_PATH

      - name: Install PDF2SVG
        run: sudo apt-get install pdf2svg

      - name: Install Pandoc
        run: sh src/pandoc.sh && pandoc --version

      - name: Build HTML
        run: npm i && make

      - name: Deploy to Github Pages
        run : |
          cd build
          git init
          git config --global user.email "support+actions@github.com"
          git config --global user.name "GitHub Actions"
          git config --global init.defaultBranch master
          git remote set-url origin ${{ env.remote }} || git remote add origin ${{ env.remote }}
          git checkout -b pages
          git add .
          git commit -m "${{ env.message }}"
          git push -u origin pages -f
